export const Affirmations = [
    "You are worthy of love and happiness.",
    "You embrace your unique journey and trust the process.",
    "Every day, you are growing stronger and more resilient.",
    "You choose to focus on the positive in your life.",
    "You have the power to create your own happiness.",
    "You are enough just as you are.",
    "You attract abundance and opportunities effortlessly.",
    "Your thoughts and beliefs shape your reality.",
    "You are deserving of success and fulfillment.",
    "You radiate confidence and self-assurance.",
    "You release negativity and welcome positivity into your life.",
    "You are capable of overcoming any challenge that comes your way.",
    "You are surrounded by love and support.",
    "You trust your intuition and listen to your inner voice.",
    "You celebrate your achievements, big and small.",
    "You are grateful for the abundance in your life.",
    "You are constantly evolving into your best self.",
    "You attract healthy and supportive relationships.",
    "You are in control of your thoughts and emotions.",
    "You are worthy of all your dreams and desires.",
    "You choose joy and peace in every situation.",
    "You are a magnet for positivity and success.",
    "You forgive yourself and release past mistakes.",
    "You are capable of making a positive impact in the world.",
    "You are a beautiful expression of life and love."
];