name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Build Server
        run: |
          npm i -g vercel

      - name: Install dependencies
        run: |
          cd Server
          pip install -r requirements.txt

      - name: Deploy Server to Vercel
        run: |
          npx vercel build --token $VERCEL_TOKEN --dir ./Server
          npx vercel deploy --token $VERCEL_TOKEN --dir ./Server